---
root: true
#  https://eslint.org/docs/rules/
env:
  node: true
  es2017: true
parserOptions:
  ecmaVersion: 10
extends:
  - "eslint:recommended"
  - prettier
rules:
  strict: [error]
  no-console: [off]
  no-constant-condition: [error, { checkLoops: false }]
